# Generated by Django 5.0.6 on 2024-06-23 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='pito',
            field=models.CharField(default='pene', max_length=255),
            preserve_default=False,
        ),
    ]
