# Generated by Django 5.0.6 on 2024-06-21 04:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='gender',
            field=models.CharField(choices=[('M', 'Men'), ('W', 'Women')], max_length=1),
        ),
        migrations.AlterField(
            model_name='productsize',
            name='size',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(7), django.core.validators.MaxValueValidator(15)]),
        ),
    ]
