# Generated by Django 5.0.6 on 2024-06-22 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_productsize_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='eccomerce/products/products_images'),
        ),
    ]
