# Generated by Django 5.0.6 on 2024-06-27 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_product_brand_alter_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(choices=[('NIKE', 'Nike'), ('ADIDAS', 'Adidas'), ('PUMA', 'Puma'), ('UNDER_ARMOUR', 'Under armour'), ('NEW_BALANCE', 'New Balance')], max_length=100),
        ),
    ]
